import RegistrationPage from "@/components/onboarding/registrationPage";


// this view is generated by a link(invite link) sent to the user, check the lib/utils.ts for the invite links ids 

// {http://localhost:3000/onboarding?inviteId=abc123xyz&schoolId=123&classId=7a}

// the link will have a query param called inviteId, which will be used to determine the role of the user
export default function Onboarding() {
  return <RegistrationPage />;
}
